apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nodejs
  endpoints:
    - path: /metrics
      port: http
      interval: 10s
  namespaceSelector:
    matchNames:
      - default
